---
- name: Playbook to deploy app on target Server
  hosts: webserver
  become: yes
  become_user: root
  tasks:
  - name: Clone a github repository
    git:
      repo: https://github.com/jekobokidou/phpsample.git
      dest: /var/www/html
      clone: yes
      update: yes
       
